### ISSUE TITLE
Assignment 1 Review

### ISSUE THREAD

**Issue by caseycull** [NyingesiePoufong/-ITC2400-Web-and-Mobile-Development-Spring-2021NEU#1]
The colors and formatting look awesome! You're meeting all the requirements there, so great job with those 🙂 

Looking at the assignment again, the professor wants you to write 4 paragraphs (1 for each season, each of which should be more than 2 sentences). In these paragraphs, they want you to describe the appearance/distinct qualities of the season, whether you like it, and whether you have any memories associated with it.

Right now, I see you have the "Lorem ipsum" text for each paragraph - if you replace this text with your own descriptions, then you'll be good to go!

**Comment by NyingesiePoufong** [comment]
> The colors and formatting look awesome! You're meeting all the requirements there, so great job with those 🙂
> 
> Looking at the assignment again, the professor wants you to write 4 paragraphs (1 for each season, each of which should be more than 2 sentences). In these paragraphs, they want you to describe the appearance/distinct qualities of the season, whether you like it, and whether you have any memories associated with it.
> 
> Right now, I see you have the "Lorem ipsum" text for each paragraph - if you replace this text with your own descriptions, then you'll be good to go!


Yes, I just finished adding those descriptions so I am going to push those in a few minutes. Thanks again for your time!

**Comment by caseycull** [comment]
Awesome, no problem!
